language: go

go:
  - 1.9

before_script:
after_script:
script:

jobs:
 include:
  - stage: coverage
    script: go test -cover ./mtcp/...
    script: go test -cover ./mudp/...
    script: go test -cover ./msocks/...
  - stage: test
    script: go test -v ./mtcp/...
    script: go test -v ./mudp/...
    script: go test -v ./msocks/...
  - stage: benchmarks
    script: go test -run=xXX -bench=. ./mtcp/...
    script: go test -run=xXX -bench=. ./mudp/...
    script: go test -run=xXX -bench=. ./msocks/...
  - stage: deploy
    script: echo "do nothing... :)"
