language: go

go:
  - 1.9

before_script:
after_script:
script:

jobs:
 include:
  - stage: coverage
    script: make coverage
  - stage: test
    script: make tests
  - stage: benchmarks
    script: make benchmarks
