ci: coverage tests benchmarks

coverage:
	go test -cover ./mtcp/...
	go test -cover ./msocks/...
	go test -cover ./internal/...
	go test -cover ./mlisten/...

tests:
	go test -v ./mtcp/...
	go test -v ./msocks/...
	go test -v ./internal/...
	go test -v ./mlisten/...

benchmarks:
	go test -run=xXX -bench=. ./mtcp/...
	go test -run=xXX -bench=. ./msocks/...
