ci: coverage tests benchmarks

coverage:
	go test -cover ./mtcp/...
	go test -cover ./mudp/...
	go test -cover ./msocks/...
	go test -cover ./internal/...
	go test -cover ./mlisten/...
	go test -cover ./certificates/...

tests:
	go test -v ./mtcp/...
	go test -v ./mudp/...
	go test -v ./msocks/...
	go test -v ./internal/...
	go test -v ./mlisten/...
	go test -v ./certificates/...

benchmarks:
	go test -run=xXX -bench=. ./mtcp/...
	go test -run=xXX -bench=. ./mudp/...
	go test -run=xXX -bench=. ./msocks/...
